### ISSUE TITLE
Noto Sans JP・Noto Serif JP専用のCSSファイルを追加

### ISSUE THREAD

**Issue by qrac** [qrac/yakuhanjp#23]
![image](https://user-images.githubusercontent.com/9658016/45197206-05b19800-b29b-11e8-9637-847f803c87c1.png)

2018年9月7日（前日に入ったり消えたりしていたが正式に？）、Google Fonts本家にNoto Sans JP・Noto Serif JPが加わった。

- [Google Fonts](https://fonts.google.com/?subset=japanese)
  - [Noto Sans JP - Google Fonts](https://fonts.google.com/specimen/Noto+Sans+JP)
    - 6ウェイト（lightが200から300に変更・300だったDemi Lightがない）
  - [Noto Serif JP - Google Fonts](https://fonts.google.com/specimen/Noto+Serif+JP)
    - 7ウェイト（100がなくなり600が追加されウェイト名がずれている）

Google Fontsはunicode-rangeで対象になる文字を分割している模様。おそらくは欧文数字・かな・漢字第○水準などで別れているか、更に細かく分類していることだろう。

- [unicode-range - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range)

Webフォントは、CSSでフォントファイルへのリンクを貼っていても対象の文字が表示されていないとファイルをダウンロードせずに済む。無数に分割していれば、その分使われている文字のフォントだけをダウンロードする状態に近づける。

早期アクセス版よりもフォント容量の削減・アクセス高速化に繋がるため、今後はGoogle Fonts本家のNoto Sans JP・Noto Serif JPを使うことが一般化していくと考えられる。

YakuHanJP・YakuHanMPは、それぞれNoto Sans・Noto Serifをベースに制作しているが、今回リリースされたGoogle Fonts本家版はウェイトの設定が若干異なる。同一ウェイトで呼び出した場合に差が出る可能性があるため検証しておく。

※ちなみに、Google FontsはIEサポートを打ち切っており、Noto SansやNoto serifは早期アクセス版を含めIEだと欧文以外が出なくなっている。

**Comment by qrac** [comment]
CodePenでテスト

- [Yaku Han JP v3.0.0 x Noto Sans JP & Noto Serif JP](https://codepen.io/qrac/pen/vzWamj)

**Comment by qrac** [comment]
![image](https://user-images.githubusercontent.com/9658016/45249389-74a1f600-b35a-11e8-9ea4-e40dff2176c5.png)

目立つのはSans-serifの300だろう。もともとのDemi LightがLightと組み合わさって約物だけ太く見えてしまう。YakuHanJP側のCSSで300をLightにする設定を行えば回避は可能。

**Comment by qrac** [comment]
Noto Sansのダウンロードページ

- [Google Noto Fonts](https://www.google.com/get/noto/)

**Comment by qrac** [comment]
## 案：CSSでSans-serifのLightを300に当てる＋Serifは順にずらす？

Sans-serifだけ6ウェイトに減るのは気持ちが悪い。その場合、浮いたDemi Lightはどうしよう。使うユーザーによってはずらしたウェイトが問題になる場合も。

やはり、Noto Sans JP・Noto Serif JP専用のCSSファイルを用意するのがもっとも安全だろう。

**Comment by qrac** [comment]
## CSSの `@font-face` でウェイトの差を揃える

### CDNバージョン

```scss
// ---------------------------------------
// Spesial Stylesheet "Yaku Han JP"
// ---------------------------------------

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 100;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Thin.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Thin.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Thin.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 300;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Light.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Light.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 400;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Regular.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Regular.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 500;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Medium.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Medium.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 700;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Bold.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Bold.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 900;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Black.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Black.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJP/YakuHanJP-Black.woff") format("woff");
}

// ---------------------------------------
// Spesial Stylesheet "Yaku Han MP"
// ---------------------------------------

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 200;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-ExtraLight.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-ExtraLight.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-ExtraLight.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 300;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Light.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Light.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 400;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Regular.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Regular.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 500;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Medium.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Medium.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 600;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-SemiBold.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-SemiBold.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-SemiBold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 700;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Bold.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Bold.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 900;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Black.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Black.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMP/YakuHanMP-Black.woff") format("woff");
}

// ---------------------------------------
// Spesial Stylesheet "Yaku Han JP s"
// ---------------------------------------

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 100;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Thin.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Thin.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Thin.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 300;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Light.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Light.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 400;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Regular.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Regular.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 500;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Medium.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Medium.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 700;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Bold.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Bold.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 900;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Black.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Black.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanJPs/YakuHanJPs-Black.woff") format("woff");
}

// ---------------------------------------
// Spesial Stylesheet "Yaku Han MP s"
// ---------------------------------------

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 200;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-ExtraLight.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-ExtraLight.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-ExtraLight.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 300;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Light.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Light.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 400;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Regular.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Regular.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 500;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Medium.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Medium.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 600;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-SemiBold.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-SemiBold.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-SemiBold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 700;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Bold.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Bold.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 900;
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Black.eot");
  src: url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Black.woff2") format("woff2"),
  url("https://cdn.jsdelivr.net/npm/yakuhanjp@3.0.0/dist/fonts/YakuHanMPs/YakuHanMPs-Black.woff") format("woff");
}
```

### ローカルバージョン

```scss
// ---------------------------------------
// Spesial Stylesheet "Yaku Han JP"
// ---------------------------------------

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 100;
  src: url("../fonts/YakuHanJP/YakuHanJP-Thin.eot");
  src: url("../fonts/YakuHanJP/YakuHanJP-Thin.woff2") format("woff2"),
  url("../fonts/YakuHanJP/YakuHanJP-Thin.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 300;
  src: url("../fonts/YakuHanJP/YakuHanJP-Light.eot");
  src: url("../fonts/YakuHanJP/YakuHanJP-Light.woff2") format("woff2"),
  url("../fonts/YakuHanJP/YakuHanJP-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 400;
  src: url("../fonts/YakuHanJP/YakuHanJP-Regular.eot");
  src: url("../fonts/YakuHanJP/YakuHanJP-Regular.woff2") format("woff2"),
  url("../fonts/YakuHanJP/YakuHanJP-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 500;
  src: url("../fonts/YakuHanJP/YakuHanJP-Medium.eot");
  src: url("../fonts/YakuHanJP/YakuHanJP-Medium.woff2") format("woff2"),
  url("../fonts/YakuHanJP/YakuHanJP-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 700;
  src: url("../fonts/YakuHanJP/YakuHanJP-Bold.eot");
  src: url("../fonts/YakuHanJP/YakuHanJP-Bold.woff2") format("woff2"),
  url("../fonts/YakuHanJP/YakuHanJP-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJP";
  font-style: normal;
  font-weight: 900;
  src: url("../fonts/YakuHanJP/YakuHanJP-Black.eot");
  src: url("../fonts/YakuHanJP/YakuHanJP-Black.woff2") format("woff2"),
  url("../fonts/YakuHanJP/YakuHanJP-Black.woff") format("woff");
}

// ---------------------------------------
// Spesial Stylesheet "Yaku Han MP"
// ---------------------------------------

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 200;
  src: url("../fonts/YakuHanMP/YakuHanMP-ExtraLight.eot");
  src: url("../fonts/YakuHanMP/YakuHanMP-ExtraLight.woff2") format("woff2"),
  url("../fonts/YakuHanMP/YakuHanMP-ExtraLight.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 300;
  src: url("../fonts/YakuHanMP/YakuHanMP-Light.eot");
  src: url("../fonts/YakuHanMP/YakuHanMP-Light.woff2") format("woff2"),
  url("../fonts/YakuHanMP/YakuHanMP-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 400;
  src: url("../fonts/YakuHanMP/YakuHanMP-Regular.eot");
  src: url("../fonts/YakuHanMP/YakuHanMP-Regular.woff2") format("woff2"),
  url("../fonts/YakuHanMP/YakuHanMP-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 500;
  src: url("../fonts/YakuHanMP/YakuHanMP-Medium.eot");
  src: url("../fonts/YakuHanMP/YakuHanMP-Medium.woff2") format("woff2"),
  url("../fonts/YakuHanMP/YakuHanMP-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 600;
  src: url("../fonts/YakuHanMP/YakuHanMP-SemiBold.eot");
  src: url("../fonts/YakuHanMP/YakuHanMP-SemiBold.woff2") format("woff2"),
  url("../fonts/YakuHanMP/YakuHanMP-SemiBold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 700;
  src: url("../fonts/YakuHanMP/YakuHanMP-Bold.eot");
  src: url("../fonts/YakuHanMP/YakuHanMP-Bold.woff2") format("woff2"),
  url("../fonts/YakuHanMP/YakuHanMP-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMP";
  font-style: normal;
  font-weight: 900;
  src: url("../fonts/YakuHanMP/YakuHanMP-Black.eot");
  src: url("../fonts/YakuHanMP/YakuHanMP-Black.woff2") format("woff2"),
  url("../fonts/YakuHanMP/YakuHanMP-Black.woff") format("woff");
}

// ---------------------------------------
// Spesial Stylesheet "Yaku Han JP s"
// ---------------------------------------

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 100;
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Thin.eot");
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Thin.woff2") format("woff2"),
  url("../fonts/YakuHanJPs/YakuHanJPs-Thin.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 300;
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Light.eot");
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Light.woff2") format("woff2"),
  url("../fonts/YakuHanJPs/YakuHanJPs-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 400;
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Regular.eot");
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Regular.woff2") format("woff2"),
  url("../fonts/YakuHanJPs/YakuHanJPs-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 500;
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Medium.eot");
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Medium.woff2") format("woff2"),
  url("../fonts/YakuHanJPs/YakuHanJPs-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 700;
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Bold.eot");
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Bold.woff2") format("woff2"),
  url("../fonts/YakuHanJPs/YakuHanJPs-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanJPs";
  font-style: normal;
  font-weight: 900;
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Black.eot");
  src: url("../fonts/YakuHanJPs/YakuHanJPs-Black.woff2") format("woff2"),
  url("../fonts/YakuHanJPs/YakuHanJPs-Black.woff") format("woff");
}

// ---------------------------------------
// Spesial Stylesheet "Yaku Han MP s"
// ---------------------------------------

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 200;
  src: url("../fonts/YakuHanMPs/YakuHanMPs-ExtraLight.eot");
  src: url("../fonts/YakuHanMPs/YakuHanMPs-ExtraLight.woff2") format("woff2"),
  url("../fonts/YakuHanMPs/YakuHanMPs-ExtraLight.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 300;
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Light.eot");
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Light.woff2") format("woff2"),
  url("../fonts/YakuHanMPs/YakuHanMPs-Light.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 400;
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Regular.eot");
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Regular.woff2") format("woff2"),
  url("../fonts/YakuHanMPs/YakuHanMPs-Regular.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 500;
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Medium.eot");
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Medium.woff2") format("woff2"),
  url("../fonts/YakuHanMPs/YakuHanMPs-Medium.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 600;
  src: url("../fonts/YakuHanMPs/YakuHanMPs-SemiBold.eot");
  src: url("../fonts/YakuHanMPs/YakuHanMPs-SemiBold.woff2") format("woff2"),
  url("../fonts/YakuHanMPs/YakuHanMPs-SemiBold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 700;
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Bold.eot");
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Bold.woff2") format("woff2"),
  url("../fonts/YakuHanMPs/YakuHanMPs-Bold.woff") format("woff");
}

@font-face {
  font-family: "YakuHanMPs";
  font-style: normal;
  font-weight: 900;
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Black.eot");
  src: url("../fonts/YakuHanMPs/YakuHanMPs-Black.woff2") format("woff2"),
  url("../fonts/YakuHanMPs/YakuHanMPs-Black.woff") format("woff");
}
```
